name: Docker Image Push for Changed Dockerfiles

on: push

jobs:

  build:
 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      working-directory: ./jupyter_pytorch
      run: docker build . --file Dockerfile --tag fatihbaltaci/jupyter
    - name: Docker Push
      run: docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker push fatihbaltaci/jupyter
