name: Docker Image CI

on: push

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      working-directory: ./python_3.6
      run: docker build . --file Dockerfile --tag fatihbaltaci/python:3.6
    - name: Docker Push
      run: docker login docker.io --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker push fatihbaltaci/python:3.6
